language: generic
sudo: required
services: 
  - docker 

before_install: 
  - docker build -t coltonumbrage/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true coltonumbrage/react-test npm test

after_success: 
  - docker build -t coltonumbrage/multi-client ./client
  - docker build -t coltonumbrage/multi-worker ./worker
  - docker build -t coltonumbrage/multi-server ./server
  - docker build -t coltonumbrage/multi-nginx ./nginx
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push coltonumbrage/multi-client
  - docker push coltonumbrage/multi-nginx
  - docker push coltonumbrage/multi-server 
  - docker push coltonumbrage/multi-worker
