name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build Docker image for the client
      - name: Build Docker Image for Client
        run: docker build -t coltonumbrage/react-test -f ./client/Dockerfile.dev ./client

      # Run tests
      - name: Run Tests
        run: docker run -e CI=true coltonumbrage/react-test npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build Docker images
      - name: Build Docker Images
        run: |
          docker build -t coltonumbrage/multi-client ./client
          docker build -t coltonumbrage/multi-worker ./worker
          docker build -t coltonumbrage/multi-server ./server
          docker build -t coltonumbrage/multi-nginx ./nginx

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Docker images to Docker Hub
      - name: Push Docker Images
        run: |
          docker push coltonumbrage/multi-client
          docker push coltonumbrage/multi-nginx
          docker push coltonumbrage/multi-server
          docker push coltonumbrage/multi-worker
