name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t coltonumbrage/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true coltonumbrage/react-test npm test

      - run: docker build -t coltonumbrage/multi-client ./client
      - run: docker build -t coltonumbrage/multi-worker ./worker
      - run: docker build -t coltonumbrage/multi-server ./server
      - run: docker build -t coltonumbrage/multi-nginx ./nginx

      #login to docker CLI
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

      - run: docker push coltonumbrage/multi-client
      - run: docker push coltonumbrage/multi-nginx
      - run: docker push coltonumbrage/multi-server
      - run: docker push coltonumbrage/multi-worker
