name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image for Client
        run: docker build -t coltonumbrage/react-test -f ./client/Dockerfile.dev ./client

      - name: Run Tests
        run: docker run -e CI=true coltonumbrage/react-test npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Images
        run: |
          docker build -t coltonumbrage/multi-client ./client
          docker build -t coltonumbrage/multi-worker ./worker
          docker build -t coltonumbrage/multi-server ./server
          docker build -t coltonumbrage/multi-nginx ./nginx

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Images
        run: |
          docker push coltonumbrage/multi-client
          docker push coltonumbrage/multi-nginx
          docker push coltonumbrage/multi-server
          docker push coltonumbrage/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-west-2-891753570665
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
